version: '3'

services:
  #контейнер с Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: dockerapp/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code:/data/mysite.local
      - ./nginx/hosts/mysite.local.conf:/etc/nginx/sites-enabled/mysite.local.conf
    networks:
      - app-network
   
  #контейнер с php    
  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: dockerapp/php
    container_name: app
    ports:
      - "9000:9000"
    volumes:
      - ./code:/data/mysite.local
      - ./fpm/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - app-network

  #контейнер с MySQL
  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/docker-entrypoint-initdb.d  
    networks:
      - app-network
      
#Docker Networks
networks:
  app-network:
    driver: bridge